In [1]:
import importlib
import utils
importlib.reload(utils) 
from utils import *

In [2]:
kaggle_cred_file = r'E:\env\KAGGLE_KEY\kaggle.json'
load_kaggle_creds(kaggle_cred_file)

In [3]:
competition = 'playground-series-s4e11'
download_competition_data(competition)

Downloading data files
Unzipping data files

In [4]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [5]:
train_file = 'data/train.csv'
train_df = pd.read_csv(train_file)

In [6]:
train_df.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,Aaradhya,Female,49.0,Ludhiana,Working Professional,Chef,NaN,5.0,NaN,NaN,2.0,More than 8 hours,Healthy,BHM,No,1.0,2.0,No,0
1,1,Vivan,Male,26.0,Varanasi,Working Professional,Teacher,NaN,4.0,NaN,NaN,3.0,Less than 5 hours,Unhealthy,LLB,Yes,7.0,3.0,No,1
2,2,Yuvraj,Male,33.0,Visakhapatnam,Student,NaN,5.0,NaN,8.97,2.0,NaN,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
3,3,Yuvraj,Male,22.0,Mumbai,Working Professional,Teacher,NaN,5.0,NaN,NaN,1.0,Less than 5 hours,Moderate,BBA,Yes,10.0,1.0,Yes,1
4,4,Rhea,Female,30.0,Kanpur,Working Professional,Business Analyst,NaN,1.0,NaN,NaN,1.0,5-6 hours,Unhealthy,BBA,Yes,9.0,4.0,Yes,0

In [33]:
train_df.columns

Index(['id', 'Name', 'Gender', 'Age', 'City',
       'Working Professional or Student', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='object')

In [35]:
student_df = train_df[train_df['Working Professional or Student'] == 'Student'].reset_index().copy()
professional_df = train_df[train_df['Working Professional or Student'] != 'Student'].reset_index().copy()

In [36]:
student_df.shape, professional_df.shape

((27901, 21), (112799, 21))

In [37]:
student_df.isna().sum()

index                                        0
id                                           0
Name                                         0
Gender                                       0
Age                                          0
City                                         0
Working Professional or Student              0
Profession                               27867
Academic Pressure                            9
Work Pressure                            27898
CGPA                                         9
Study Satisfaction                          10
Job Satisfaction                         27893
Sleep Duration                               0
Dietary Habits                               2
Degree                                       0
Have you ever had suicidal thoughts ?        0
Work/Study Hours                             0
Financial Stress                             3
Family History of Mental Illness             0
Depression                                   0
dtype: int64

In [38]:
professional_df.isna().sum()

index                                         0
id                                            0
Name                                          0
Gender                                        0
Age                                           0
City                                          0
Working Professional or Student               0
Profession                                 8763
Academic Pressure                        112794
Work Pressure                                20
CGPA                                     112793
Study Satisfaction                       112793
Job Satisfaction                             17
Sleep Duration                                0
Dietary Habits                                2
Degree                                        2
Have you ever had suicidal thoughts ?         0
Work/Study Hours                              0
Financial Stress                              1
Family History of Mental Illness              0
Depression                                    0
dtype: int64

In [25]:
train_df.Name.value_counts().head().to_dict()

{'Rohan': 3178, 'Aarav': 2336, 'Rupak': 2176, 'Aaradhya': 2045, 'Anvi': 2035}

In [31]:
def create_data_summary(df):
    isna_count = df.isna().sum()
    n_unique = pd.Series({col: df[col].nunique() for col in df.columns})
    dtypes = df.dtypes
    value_counts_top_5 = pd.Series({col: df[col].value_counts().head(5).to_dict() for col in df.columns})
    output = pd.DataFrame(dict(isna_count=isna_count, n_unique=n_unique, dtypes=dtypes, value_counts_top_5=value_counts_top_5))
    return output

In [32]:
data_summary = create_data_summary(train_df)

In [28]:
data_summary

,isna_count,n_unique,dtypes,value_counts_top_10
id,0,140700,int64,"{140699: 1, 0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1..."
Name,0,422,object,"{'Rohan': 3178, 'Aarav': 2336, 'Rupak': 2176, ..."
Gender,0,2,object,"{'Male': 77464, 'Female': 63236}"
Age,0,43,float64,"{56.0: 5246, 49.0: 5099, 38.0: 4564, 53.0: 452..."
City,0,98,object,"{'Kalyan': 6591, 'Patna': 5924, 'Vasai-Virar':..."
Working Professional or Student,0,2,object,"{'Working Professional': 112799, 'Student': 27..."
Profession,36630,64,object,"{'Teacher': 24906, 'Content Writer': 7814, 'Ar..."
Academic Pressure,112803,5,float64,"{3.0: 7463, 5.0: 6296, 4.0: 5158, 1.0: 4801, 2..."
Work Pressure,27918,5,float64,"{2.0: 24373, 4.0: 22512, 5.0: 22436, 3.0: 2189..."
CGPA,112802,331,float64,"{8.04: 822, 9.96: 425, 5.74: 410, 8.95: 371, 9..."
Study Satisfaction,112803,5,float64,"{4.0: 6360, 2.0: 5840, 3.0: 5823, 1.0: 5451, 5..."
Job Satisfaction,27910,5,float64,"{2.0: 24783, 5.0: 22812, 1.0: 22324, 3.0: 2195..."
Sleep Duration,0,36,object,"{'Less than 5 hours': 38784, '7-8 hours': 3696..."
Dietary Habits,4,23,object,"{'Moderate': 49705, 'Unhealthy': 46227, 'Healt..."
Degree,2,115,object,"{'Class 12': 14729, 'B.Ed': 11691, 'B.Arch': 8..."
Have you ever had suicidal thoughts ?,0,2,object,"{'No': 71138, 'Yes': 69562}"
Work/Study Hours,0,13,float64,"{10.0: 14199, 11.0: 12832, 9.0: 12711, 0.0: 12..."
Financial Stress,4,5,float64,"{2.0: 31451, 5.0: 28279, 4.0: 27765, 1.0: 2721..."
Family History of Mental Illness,0,2,object,"{'No': 70758, 'Yes': 69942}"
Depression,0,2,int64,"{0: 115133, 1: 25567}"

In [15]:
type(train_df.dtypes)

pandas.core.series.Series

In [10]:
for col in train_df.columns:

pandas.core.series.Series